---

# Add the sensuGo agent repository
- name: Adding sensuGo-agent repository
  get_url:
    url: "{{ item }}"
    dest: "/etc/apt/sources.list.d/sensu_stable.list"
  with_items:
    - "{{ sensuGo_agent_repo }}"

# Add gpgkey
- name: Add SensuGo repository key
  apt_key:
    url: "{{ sensuGo_agent_gpgkey }}"
    state: present

# Install requested sensuGo-agent version
- name: Installing sensuGo-agent
  become: 'yes'
  apt:
    name:
      - sensu-go-agent
    state: latest
    update_cache: yes
  register: sensuGo_agent_install

# Enable systemctl for sensuGo-agent if service module is "systemctl"
- name: sensuGo-agent systemctl enable if service module is systemctl
  become: 'yes'
  systemd:
    name: "{{ item }}"
    enabled: 'yes'
  with_items:
    - sensu-agent
  when: ansible_service_mgr == 'systemd'


# Enable sysvinit for sensuGo-agent if service module is "sysvinit"
- name: sensuGo-agent sysvinit enable if service module is sysvinit
  become: 'yes'
  sysvinit:
    name: "{{ item }}"
    enabled: 'yes'
  with_items:
    - sensu-agent
  when: ansible_service_mgr == 'sysvinit'


# Configure sensu-agent
- name: Config agent.yml
  template:
    src: agent.yml.j2
    dest: /etc/sensu/agent.yml
    owner: root
    group: root
    mode: 0644
  when: sensuGo_agent_install is succeeded
  register: sensuGo_agent_config
  notify:
    - sensuGo-agent restart

# giving superpowers to sensu-agent
- name: Creating sudo access
  copy:
    dest: /etc/sudoers.d/sensu
    content: "sensu ALL=(ALL) NOPASSWD:ALL"
    owner: root
    group: root
  when: sensuGo_sudo_access == true
